services:
    app:
        build:
            args:
                user: 1000
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: astro-be
        container_name: astro-be
        restart: unless-stopped
        working_dir: /var/www/
        user: www-data
        volumes:
            - ./:/var/www
        networks:
            - astro-network
networks:
    astro-network:
        driver: bridge
